# Generated by Django 4.0.4 on 2023-04-06 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('pro_image', models.ImageField(upload_to='product/')),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('desc', models.TextField(blank=True, default=0, max_length=255, null=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flipkart.category')),
            ],
        ),
    ]
